### ISSUE TITLE
Better error message if file doesn't exist

### ISSUE THREAD

**Issue by dadah89** [osheroff/git-spelunk#22]
```
git spelunk ops
/opt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git_spelunk-0.4.0/lib/git_spelunk/file_context.rb:59:in `get_line_commit_info': undefined method `commit' for nil:NilClass (NoMethodError)
	from /opt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git_spelunk-0.4.0/lib/git_spelunk/ui.rb:59:in `set_repo_content'
	from /opt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git_spelunk-0.4.0/lib/git_spelunk/ui.rb:17:in `block in initialize'
	from /opt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/dispel-0.0.7/lib/dispel/screen.rb:24:in `open'
	from /opt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/dispel-0.0.7/lib/dispel/screen.rb:13:in `open'
	from /opt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git_spelunk-0.4.0/lib/git_spelunk/ui.rb:8:in `initialize'
	from /opt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git_spelunk-0.4.0/bin/git-spelunk:40:in `new'
	from /opt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git_spelunk-0.4.0/bin/git-spelunk:40:in `<top (required)>'
	from /opt/.rbenv/versions/2.2.3/bin/git-spelunk:23:in `load'
	from /opt/.rbenv/versions/2.2.3/bin/git-spelunk:23:in `<main>'
```

**Comment by osheroff** [comment]
fixed in 0.4.1
